application:
  title: Job Offers by JJR
  version: 0.0.1

spring:
  data:
    mongodb:
      host: 192.168.21.246
      port: 27017
      username: dummy_name
      password: dummy_password
      database: job-offers
